export const items = {
  excavation_upto_8ft_depth: {
    itemNo: 0,
    date: "",
    particulars:
      "Earth work in excavation for all kind of soil, by mechanical means (Hydraulic excavator)/  manual  means  over  areas including  loading and unloading for disposal/stacking of excavated earth for lead upto 1km or within the site campus and for all lifts as directed by Engineer-in- charge - upto 2.5 mt excavation depth",
    measurements: [],
    total: 0,
    unit: "cmt",
  },
  rubble_solling_at_plinth_lvl: {
    itemNo: 0,
    date: "",
    particulars: "RUBBLE SOLLING at plinth lvl",
    measurements: [
      {
        description: "soling for grade slab",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  pile_450mm_dia_7mt_depth_labour: {
    itemNo: 0,
    date: "",
    particulars: "450mm dia Pile - 7 mt depth from FGL - labour for pile",
    measurements: [
      {
        description: "doble pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "rmt",
  },
  pcc_m10_grade_1_3_6: {
    itemNo: 0,
    date: "",
    particulars: "PCC - M10 grade - (1:3:6)",
    measurements: [
      {
        description: "PCC for GB horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vartical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "intarnal vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Shed area PCC for trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  back_filling_excavated_earth: {
    itemNo: 0,
    date: "",
    particulars: "Back filling with available excavated earth",
    measurements: [],
    total: 0,
    unit: "cmt",
  },
  filling_good_soil_outside: {
    itemNo: 0,
    date: "",
    particulars: "Filling with good soil brought from outiside",
    measurements: [
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  m25_concrete_pile_6_4mt: {
    itemNo: 0,
    date: "",
    particulars: "M25 concrete for Pile - 6.4 mt length",
    measurements: [
      {
        description: "double pile",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal pile",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_ground_beam_pile_cap_m25: {
    itemNo: 0,
    date: "",
    particulars: "RCC ground beam and pile cap- M25 grade (Including formwork)",
    measurements: [
      {
        description: "horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vartical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "intarnal vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "pile cap double",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_column_plinth_to_1st_slab_m25: {
    itemNo: 0,
    date: "",
    particulars:
      "RCC column from plinth lvl to 1st slab (4.2mt ht)- M25 grade (Including formwork)",
    measurements: [
      {
        description: "C1",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C2",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C3",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C4",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C5",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C6",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_column_beam_dome_m25: {
    itemNo: 0,
    date: "",
    particulars:
      "RCC column and beam for dome above 1st slab (4.2mt ht)- M25 grade (Including formwork)",
    measurements: [
      {
        description: "peripherial column only",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  trimix_m25_grade_concrete: {
    itemNo: 0,
    date: "",
    particulars: "Trimix - M25 Grade concrete",
    measurements: [
      {
        description: "Trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  trimix_labour_groove_cutting: {
    itemNo: 0,
    date: "",
    particulars: "Trimix - labour only with groove/cutting",
    measurements: [
      {
        description: "Trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "smt",
  },
  brick_work_plinth_to_1st_slab: {
    itemNo: 0,
    date: "",
    particulars:
      "Brick work below plinth and from plinth to 1st slab of 4.2 mt ht",
    measurements: [
      {
        description: "brick below plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "compound",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_beam_slab_4_2mt_m25: {
    itemNo: 0,
    date: "",
    particulars: "RCC for beam and slab at 4.2 mt lvl - M 25 grade",
    measurements: [
      {
        description: "horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "slab",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  plaster_inner_outer_1st_slab: {
    itemNo: 0,
    date: "",
    particulars: "plaster inner and outer upto 1st slab lvl (double coat)",
    measurements: [
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "compound",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "ceiling plaster",
        nos: 0,
        length: 0,
        breadth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "smt",
  },
  brick_work_1st_slab_to_gutter: {
    itemNo: 0,
    date: "",
    particulars: "Brick work from 1st slab to gutter lvl",
    measurements: [
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  m25_coping_beam_gutter: {
    itemNo: 0,
    date: "",
    particulars:
      "M25 concrte for Coping beam/lintel beam above brick work and gutter",
    measurements: [
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "compound",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "gutter",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  steel_fe500: {
    itemNo: 0,
    date: "",
    particulars: "steel - Fe500",
    measurements: [
      {
        description: "plinth area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Slab area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "Kg",
  },
  ug_water_tank_rcc: {
    itemNo: 0,
    date: "",
    particulars: "U.G. water tank - RCC as per design",
    measurements: [],
    total: 0,
    unit: "Lit",
  },
  overhead_water_tank_pvc: {
    itemNo: 0,
    date: "",
    particulars: "Over head water tank (PVC)",
    measurements: [],
    total: 0,
    unit: "Lit",
  },
  gp2_grout: {
    itemNo: 0,
    date: "",
    particulars: "GP2 grout",
    measurements: [],
    total: 0,
    unit: "cft",
  },
  slab_3mt_height_m25: {
    itemNo: 0,
    date: "",
    particulars: "Slab at 3 mt height M 25 grade concrete",
    measurements: [
      {
        description: "vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "horizonatal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Slab area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  toilet_wash_room_ground_floor: {
    itemNo: 0,
    date: "",
    particulars:
      "toilet/wash room at gr floor including flooring+dedo+urinal+WC+wash basin otheer fiiting",
    measurements: [
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
    ],
    total: 0,
    unit: "smt",
  },
  electric_work_toilet_ground_floor: {
    itemNo: 0,
    date: "",
    particulars: "electric work toilet/wash room at gr floor",
    measurements: [],
    total: 0,
    unit: "sft",
  },
  khar_kuva_septic_tank_brick: {
    itemNo: 0,
    date: "",
    particulars: "Khar kuva and septic tank in brick work",
    measurements: [{ description: "", nos: 0, area: 0 }],
    total: 0,
    unit: "no",
  },
};
