// export const items = {
//   excavation_upto_8ft_depth: {
//     itemNo: 1,
//     date: "20/02/2018",
//     particulars: "EXCAVATION upto 8' depth from N.G.L",
//     measurements: [],
//     total: 0.0,
//     unit: "cmt",
//   },
//   rubble_solling_at_plinth_lvl: {
//     itemNo: 2,
//     date: "20/02/2018",
//     particulars: "RUBBLE SOLLING at plinth lvl",
//     measurements: [
//       {
//         description: "soling for grade slab",
//         nos: 1,
//         length: 51.6,
//         breadth: 21.23,
//         depth: 0.2,
//         area: 219.09,
//       },
//     ],
//     total: 219.09,
//     unit: "cmt",
//   },
//   pile_450mm_dia_7mt_depth_labour: {
//     itemNo: 3,
//     date: "20/02/2018",
//     particulars: "450mm dia Pile - 7 mt depth from FGL - labour for pile",
//     measurements: [
//       {
//         description: "doble pile",
//         nos: 2,
//         length: 28.0,
//         depth: 7.0,
//         area: 392.0,
//       },
//       {
//         description: "single pile",
//         nos: 1,
//         length: 9.0,
//         depth: 7.0,
//         area: 63.0,
//       },
//       {
//         description: "tripal pile",
//         nos: 3,
//         length: 8.0,
//         depth: 7.0,
//         area: 168.0,
//       },
//     ],
//     total: 623.0,
//     unit: "rmt",
//   },
//   pcc_m10_grade_1_3_6: {
//     itemNo: 4,
//     date: "15/03/2023",
//     particulars: "PCC - M10 grade - (1:3:6)",
//     measurements: [
//       {
//         description: "PCC for GB horizontal",
//         nos: 8,
//         length: 21.23,
//         breadth: 0.38,
//         depth: 0.1,
//         area: 6.454,
//       },
//       {
//         description: "",
//         nos: 4,
//         length: 5.5,
//         breadth: 0.38,
//         depth: 0.1,
//         area: 0.836,
//       },
//       {
//         description: "vartical",
//         nos: 8,
//         length: 5.7,
//         breadth: 0.38,
//         depth: 0.1,
//         area: 1.733,
//       },
//       {
//         description: "",
//         nos: 8,
//         length: 5.7,
//         breadth: 0.38,
//         depth: 0.1,
//         area: 1.733,
//       },
//       {
//         description: "intarnal vertical",
//         nos: 11,
//         length: 5.7,
//         breadth: 0.38,
//         depth: 0.1,
//         area: 2.383,
//       },
//       {
//         description: "Shed area PCC for trimix",
//         nos: 1,
//         length: 51.6,
//         breadth: 21.23,
//         depth: 0.1,
//         area: 109.55,
//       },
//     ],
//     total: 122.68,
//     unit: "cmt",
//   },
//   back_filling_excavated_earth: {
//     itemNo: 5,
//     date: "28/02/2018",
//     particulars: "Back filling with available excavated earth",
//     measurements: [],
//     total: 0.0,
//     unit: "cmt",
//   },
//   filling_good_soil_outside: {
//     itemNo: 6,
//     date: "28/02/2018",
//     particulars: "Filling with good soil brought from outiside",
//     measurements: [
//       {
//         description: "",
//         nos: 0,
//         length: 51.6,
//         breadth: 21.23,
//         depth: 0.15,
//         area: 0.0,
//       },
//     ],
//     total: 0.0,
//     unit: "cmt",
//   },
//   m25_concrete_pile_6_4mt: {
//     itemNo: 7,
//     date: "15/03/2023",
//     particulars: "M25 concrete for Pile - 6.4 mt length",
//     measurements: [
//       {
//         description: "double pile",
//         nos: 8,
//         length: 7.0,
//         breadth: 0.16,
//         depth: 6.4,
//         area: 56.97,
//       },
//       {
//         description: "single",
//         nos: 1,
//         length: 9.0,
//         breadth: 0.16,
//         depth: 6.4,
//         area: 9.16,
//       },
//       {
//         description: "tripal pile",
//         nos: 3,
//         length: 8.0,
//         breadth: 0.16,
//         depth: 6.4,
//         area: 24.42,
//       },
//     ],
//     total: 90.55,
//     unit: "cmt",
//   },
//   rcc_ground_beam_pile_cap_m25: {
//     itemNo: 8,
//     date: "15/03/2023",
//     particulars: "RCC ground beam and pile cap- M25 grade (Including formwork)",
//     measurements: [
//       {
//         description: "horizontal",
//         nos: 8,
//         length: 21.23,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 17.578,
//       },
//       {
//         description: "",
//         nos: 4,
//         length: 5.5,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 2.277,
//       },
//       {
//         description: "vartical",
//         nos: 8,
//         length: 5.7,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 4.72,
//       },
//       {
//         description: "",
//         nos: 8,
//         length: 5.7,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 4.72,
//       },
//       {
//         description: "intarnal vertical",
//         nos: 11,
//         length: 5.7,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 6.489,
//       },
//       {
//         description: "pile cap double",
//         nos: 28,
//         length: 2.0,
//         breadth: 0.6,
//         depth: 0.75,
//         area: 25.2,
//       },
//       {
//         description: "single",
//         nos: 9,
//         length: 0.6,
//         breadth: 0.45,
//         depth: 0.6,
//         area: 1.46,
//       },
//       {
//         description: "tripal",
//         nos: 8,
//         length: 3.0,
//         breadth: 0.6,
//         depth: 0.75,
//         area: 10.8,
//       },
//     ],
//     total: 73.24,
//     unit: "cmt",
//   },
//   rcc_column_plinth_to_1st_slab_m25: {
//     itemNo: 9,
//     date: "15/03/2023",
//     particulars:
//       "RCC column from plinth lvl to 1st slab (4.2mt ht)- M25 grade (Including formwork)",
//     measurements: [
//       {
//         description: "C1",
//         nos: 4,
//         length: 0.3,
//         breadth: 0.6,
//         depth: 3.75,
//         area: 2.7,
//       },
//       {
//         description: "C2",
//         nos: 14,
//         length: 0.38,
//         breadth: 0.38,
//         depth: 3.75,
//         area: 7.58,
//       },
//       {
//         description: "C3",
//         nos: 4,
//         length: 0.38,
//         breadth: 0.6,
//         depth: 3.75,
//         area: 3.42,
//       },
//       {
//         description: "C4",
//         nos: 4,
//         length: 0.38,
//         breadth: 0.6,
//         depth: 3.75,
//         area: 3.42,
//       },
//       {
//         description: "C5",
//         nos: 4,
//         length: 0.38,
//         breadth: 0.6,
//         depth: 3.75,
//         area: 3.42,
//       },
//       {
//         description: "C6",
//         nos: 6,
//         length: 0.38,
//         breadth: 0.6,
//         depth: 3.75,
//         area: 5.13,
//       },
//     ],
//     total: 25.67,
//     unit: "cmt",
//   },
//   rcc_column_beam_dome_m25: {
//     itemNo: 10,
//     date: "15/03/2023",
//     particulars:
//       "RCC column and beam for dome above 1st slab (4.2mt ht)- M25 grade (Including formwork)",
//     measurements: [
//       {
//         description: "peripherial column only",
//         nos: 22,
//         length: 0.3,
//         breadth: 0.6,
//         depth: 3.0,
//         area: 11.88,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 51.64,
//         breadth: 0.23,
//         depth: 1.15,
//         area: 13.66,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 51.64,
//         breadth: 0.23,
//         depth: 0.7,
//         area: 8.31,
//       },
//     ],
//     total: 33.85,
//     unit: "cmt",
//   },
//   trimix_m25_grade_concrete: {
//     itemNo: 11,
//     date: "15/03/2023",
//     particulars: "Trimix - M25 Grade concrete",
//     measurements: [
//       {
//         description: "Trimix",
//         nos: 1,
//         length: 51.6,
//         breadth: 21.23,
//         depth: 0.15,
//         area: 164.32,
//       },
//     ],
//     total: 164.32,
//     unit: "cmt",
//   },
//   trimix_labour_groove_cutting: {
//     itemNo: 12,
//     date: "15/03/2023",
//     particulars: "Trimix - labour only with groove/cutting",
//     measurements: [
//       {
//         description: "Trimix",
//         nos: 1,
//         length: 51.6,
//         breadth: 21.23,
//         area: 1095.47,
//       },
//     ],
//     total: 1095.47,
//     unit: "smt",
//   },
//   brick_work_plinth_to_1st_slab: {
//     itemNo: 13,
//     date: "15/03/2023",
//     particulars:
//       "Brick work below plinth and from plinth to 1st slab of 4.2 mt ht",
//     measurements: [
//       {
//         description: "brick below plinth",
//         nos: 2,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 10.68,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 21.23,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 4.39,
//       },
//       {
//         description: "brick above plinth",
//         nos: 1,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 3.75,
//         area: 44.51,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 2.85,
//         area: 33.82,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 16.8,
//         breadth: 0.23,
//         depth: 3.75,
//         area: 28.98,
//       },
//       {
//         description: "compound",
//         nos: 1,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 1.12,
//         area: 13.29,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 21.5,
//         breadth: 0.23,
//         depth: 1.12,
//         area: 5.54,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 11.5,
//         breadth: 0.23,
//         depth: 1.12,
//         area: 2.96,
//       },
//       {
//         description: "toilet wall",
//         nos: 3,
//         length: 1.5,
//         breadth: 0.23,
//         depth: 3.0,
//         area: 3.11,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 5.0,
//         breadth: 0.23,
//         depth: 3.0,
//         area: 3.45,
//       },
//     ],
//     total: 150.73,
//     unit: "cmt",
//   },
//   rcc_beam_slab_4_2mt_m25: {
//     itemNo: 14,
//     date: "15/03/2023",
//     particulars: "RCC for beam and slab at 4.2 mt lvl - M 25 grade",
//     measurements: [
//       {
//         description: "horizontal",
//         nos: 7,
//         length: 16.5,
//         breadth: 0.38,
//         depth: 0.45,
//         area: 19.75,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 16.5,
//         breadth: 0.23,
//         depth: 0.6,
//         area: 2.28,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 16.5,
//         breadth: 0.3,
//         depth: 0.6,
//         area: 2.97,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 16.5,
//         breadth: 0.35,
//         depth: 0.6,
//         area: 3.47,
//       },
//       {
//         description: "vertical",
//         nos: 7,
//         length: 40.0,
//         breadth: 0.23,
//         depth: 0.45,
//         area: 28.98,
//       },
//       {
//         description: "",
//         nos: 7,
//         length: 9.3,
//         breadth: 0.23,
//         depth: 0.6,
//         area: 8.98,
//       },
//       {
//         description: "slab",
//         nos: 1,
//         length: 49.5,
//         breadth: 16.8,
//         depth: 0.23,
//         area: 187.11,
//       },
//     ],
//     total: 253.54,
//     unit: "cmt",
//   },
//   plaster_inner_outer_1st_slab: {
//     itemNo: 15,
//     date: "15/03/2023",
//     particulars: "plaster inner and outer upto 1st slab lvl (double coat)",
//     measurements: [
//       {
//         description: "brick above plinth",
//         nos: 2,
//         length: 51.6,
//         depth: 3.75,
//         area: 387.0,
//       },
//       { description: "", nos: 2, length: 51.6, depth: 2.85, area: 294.12 },
//       { description: "", nos: 4, length: 16.8, depth: 3.75, area: 252.0 },
//       {
//         description: "compound",
//         nos: 2,
//         length: 51.6,
//         depth: 1.12,
//         area: 115.58,
//       },
//       { description: "", nos: 2, length: 21.5, depth: 1.12, area: 48.16 },
//       { description: "", nos: 2, length: 11.5, depth: 1.12, area: 25.76 },
//       {
//         description: "toilet wall",
//         nos: 6,
//         length: 1.5,
//         depth: 3.0,
//         area: 27.0,
//       },
//       { description: "", nos: 2, length: 5.0, depth: 3.0, area: 30.0 },
//       {
//         description: "ceiling plaster",
//         nos: 1,
//         length: 49.3,
//         breadth: 16.8,
//         area: 828.24,
//       },
//     ],
//     total: 2007.86,
//     unit: "smt",
//   },
//   brick_work_1st_slab_to_gutter: {
//     itemNo: 16,
//     date: "15/03/2023",
//     particulars: "Brick work from 1st slab to gutter lvl",
//     measurements: [
//       {
//         description: "",
//         nos: 1,
//         length: 51.64,
//         breadth: 0.23,
//         depth: 3.0,
//         area: 35.63,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 51.64,
//         breadth: 0.23,
//         depth: 1.95,
//         area: 23.16,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 16.8,
//         breadth: 0.23,
//         depth: 3.0,
//         area: 23.18,
//       },
//     ],
//     total: 81.98,
//     unit: "cmt",
//   },
//   m25_coping_beam_gutter: {
//     itemNo: 17,
//     date: "15/03/2023",
//     particulars:
//       "M25 concrte for Coping beam/lintel beam above brick work and gutter",
//     measurements: [
//       {
//         description: "brick above plinth",
//         nos: 2,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 3.56,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 3.56,
//       },
//       {
//         description: "",
//         nos: 4,
//         length: 16.8,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 2.32,
//       },
//       {
//         description: "compound",
//         nos: 2,
//         length: 51.6,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 3.56,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 21.5,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 1.48,
//       },
//       {
//         description: "",
//         nos: 2,
//         length: 11.5,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 0.79,
//       },
//       {
//         description: "toilet wall",
//         nos: 3,
//         length: 1.5,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 0.16,
//       },
//       {
//         description: "",
//         nos: 1,
//         length: 5.0,
//         breadth: 0.23,
//         depth: 0.15,
//         area: 0.17,
//       },
//       {
//         description: "gutter",
//         nos: 2,
//         length: 51.64,
//         breadth: 1.2,
//         depth: 0.15,
//         area: 18.59,
//       },
//     ],
//     total: 34.19,
//     unit: "cmt",
//   },
//   steel_fe500: {
//     itemNo: 18,
//     date: "15/03/2023",
//     particulars: "steel - Fe500",
//     measurements: [
//       {
//         description: "plinth area",
//         nos: 1,
//         length: 51.6,
//         breadth: 21.23,
//         depth: 16.14,
//         area: 17680.85,
//       },
//       {
//         description: "Slab area",
//         nos: 1,
//         length: 49.3,
//         breadth: 16.8,
//         depth: 26.9,
//         area: 22279.66,
//       },
//     ],
//     total: 39960.51,
//     unit: "Kg",
//   },
//   ug_water_tank_rcc: {
//     itemNo: 19,
//     date: "15/03/2023",
//     particulars: "U.G. water tank - RCC as per design",
//     measurements: [],
//     total: 0.0,
//     unit: "Lit",
//   },
//   overhead_water_tank_pvc: {
//     itemNo: 20,
//     date: "15/03/2023",
//     particulars: "Over head water tank (PVC)",
//     measurements: [],
//     total: 0.0,
//     unit: "Lit",
//   },
//   gp2_grout: {
//     itemNo: 21,
//     date: "15/03/2023",
//     particulars: "GP2 grout",
//     measurements: [],
//     total: 0.0,
//     unit: "cft",
//   },
//   slab_3mt_height_m25: {
//     itemNo: 22,
//     date: "15/03/2023",
//     particulars: "Slab at 3 mt height M 25 grade concrete",
//     measurements: [
//       {
//         description: "vertical",
//         nos: 7,
//         length: 3.1,
//         breadth: 0.23,
//         depth: 0.6,
//         area: 4.99,
//       },
//       {
//         description: "horizonatal",
//         nos: 2,
//         length: 21.23,
//         breadth: 0.23,
//         depth: 0.6,
//         area: 9.77,
//       },
//       {
//         description: "Slab area",
//         nos: 1,
//         length: 21.23,
//         breadth: 3.1,
//         depth: 0.15,
//         area: 65.81,
//       },
//     ],
//     total: 80.57,
//     unit: "cmt",
//   },
//   toilet_wash_room_ground_floor: {
//     itemNo: 23,
//     date: "15/03/2023",
//     particulars:
//       "toilet/wash room at gr floor including flooring+dedo+urinal+WC+wash basin otheer fiiting",
//     measurements: [
//       { description: "", nos: 3, length: 1.05, breadth: 1.09, area: 3.42 },
//       { description: "", nos: 1, length: 1.2, breadth: 1.09, area: 1.3 },
//       { description: "", nos: 1, length: 3.7, breadth: 1.5, area: 5.55 },
//     ],
//     total: 10.27,
//     unit: "smt",
//   },
//   electric_work_toilet_ground_floor: {
//     itemNo: 25,
//     date: "15/03/2023",
//     particulars: "electric work toilet/wash room at gr floor",
//     measurements: [],
//     total: 0.0,
//     unit: "sft",
//   },
//   khar_kuva_septic_tank_brick: {
//     itemNo: 26,
//     date: "15/03/2023",
//     particulars: "Khar kuva and septic tank in brick work",
//     measurements: [{ description: "", nos: 1, area: 1.0 }],
//     total: 1.0,
//     unit: "no",
//   },
// };



export const items = {
  excavation_upto_8ft_depth: {
    itemNo: 0,
    date: "",
    particulars: "EXCAVATION upto 8' depth from N.G.L",
    measurements: [],
    total: 0,
    unit: "cmt",
  },
  rubble_solling_at_plinth_lvl: {
    itemNo: 0,
    date: "",
    particulars: "RUBBLE SOLLING at plinth lvl",
    measurements: [
      {
        description: "soling for grade slab",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  pile_450mm_dia_7mt_depth_labour: {
    itemNo: 0,
    date: "",
    particulars: "450mm dia Pile - 7 mt depth from FGL - labour for pile",
    measurements: [
      {
        description: "doble pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal pile",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "rmt",
  },
  pcc_m10_grade_1_3_6: {
    itemNo: 0,
    date: "",
    particulars: "PCC - M10 grade - (1:3:6)",
    measurements: [
      {
        description: "PCC for GB horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vartical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "intarnal vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Shed area PCC for trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  back_filling_excavated_earth: {
    itemNo: 0,
    date: "",
    particulars: "Back filling with available excavated earth",
    measurements: [],
    total: 0,
    unit: "cmt",
  },
  filling_good_soil_outside: {
    itemNo: 0,
    date: "",
    particulars: "Filling with good soil brought from outiside",
    measurements: [
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  m25_concrete_pile_6_4mt: {
    itemNo: 0,
    date: "",
    particulars: "M25 concrete for Pile - 6.4 mt length",
    measurements: [
      {
        description: "double pile",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal pile",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_ground_beam_pile_cap_m25: {
    itemNo: 0,
    date: "",
    particulars: "RCC ground beam and pile cap- M25 grade (Including formwork)",
    measurements: [
      {
        description: "horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vartical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "intarnal vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "pile cap double",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "single",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "tripal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_column_plinth_to_1st_slab_m25: {
    itemNo: 0,
    date: "",
    particulars:
      "RCC column from plinth lvl to 1st slab (4.2mt ht)- M25 grade (Including formwork)",
    measurements: [
      {
        description: "C1",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C2",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C3",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C4",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C5",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "C6",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_column_beam_dome_m25: {
    itemNo: 0,
    date: "",
    particulars:
      "RCC column and beam for dome above 1st slab (4.2mt ht)- M25 grade (Including formwork)",
    measurements: [
      {
        description: "peripherial column only",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  trimix_m25_grade_concrete: {
    itemNo: 0,
    date: "",
    particulars: "Trimix - M25 Grade concrete",
    measurements: [
      {
        description: "Trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  trimix_labour_groove_cutting: {
    itemNo: 0,
    date: "",
    particulars: "Trimix - labour only with groove/cutting",
    measurements: [
      {
        description: "Trimix",
        nos: 0,
        length: 0,
        breadth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "smt",
  },
  brick_work_plinth_to_1st_slab: {
    itemNo: 0,
    date: "",
    particulars:
      "Brick work below plinth and from plinth to 1st slab of 4.2 mt ht",
    measurements: [
      {
        description: "brick below plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "compound",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  rcc_beam_slab_4_2mt_m25: {
    itemNo: 0,
    date: "",
    particulars: "RCC for beam and slab at 4.2 mt lvl - M 25 grade",
    measurements: [
      {
        description: "horizontal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "slab",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  plaster_inner_outer_1st_slab: {
    itemNo: 0,
    date: "",
    particulars: "plaster inner and outer upto 1st slab lvl (double coat)",
    measurements: [
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "compound",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        depth: 0,
        area: 0,
      },
      { description: "", nos: 0, length: 0, depth: 0, area: 0 },
      {
        description: "ceiling plaster",
        nos: 0,
        length: 0,
        breadth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "smt",
  },
  brick_work_1st_slab_to_gutter: {
    itemNo: 0,
    date: "",
    particulars: "Brick work from 1st slab to gutter lvl",
    measurements: [
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  m25_coping_beam_gutter: {
    itemNo: 0,
    date: "",
    particulars:
      "M25 concrte for Coping beam/lintel beam above brick work and gutter",
    measurements: [
      {
        description: "brick above plinth",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "compound",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "toilet wall",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "gutter",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  steel_fe500: {
    itemNo: 0,
    date: "",
    particulars: "steel - Fe500",
    measurements: [
      {
        description: "plinth area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Slab area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "Kg",
  },
  ug_water_tank_rcc: {
    itemNo: 0,
    date: "",
    particulars: "U.G. water tank - RCC as per design",
    measurements: [],
    total: 0,
    unit: "Lit",
  },
  overhead_water_tank_pvc: {
    itemNo: 0,
    date: "",
    particulars: "Over head water tank (PVC)",
    measurements: [],
    total: 0,
    unit: "Lit",
  },
  gp2_grout: {
    itemNo: 0,
    date: "",
    particulars: "GP2 grout",
    measurements: [],
    total: 0,
    unit: "cft",
  },
  slab_3mt_height_m25: {
    itemNo: 0,
    date: "",
    particulars: "Slab at 3 mt height M 25 grade concrete",
    measurements: [
      {
        description: "vertical",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "horizonatal",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
      {
        description: "Slab area",
        nos: 0,
        length: 0,
        breadth: 0,
        depth: 0,
        area: 0,
      },
    ],
    total: 0,
    unit: "cmt",
  },
  toilet_wash_room_ground_floor: {
    itemNo: 0,
    date: "",
    particulars:
      "toilet/wash room at gr floor including flooring+dedo+urinal+WC+wash basin otheer fiiting",
    measurements: [
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
      { description: "", nos: 0, length: 0, breadth: 0, area: 0 },
    ],
    total: 0,
    unit: "smt",
  },
  electric_work_toilet_ground_floor: {
    itemNo: 0,
    date: "",
    particulars: "electric work toilet/wash room at gr floor",
    measurements: [],
    total: 0,
    unit: "sft",
  },
  khar_kuva_septic_tank_brick: {
    itemNo: 0,
    date: "",
    particulars: "Khar kuva and septic tank in brick work",
    measurements: [{ description: "", nos: 0, area: 0 }],
    total: 0,
    unit: "no",
  },
};